scp -i ~/khes.pem rs7:/home/www/data/standards/marcxml/frbr/frbr2html.xsl standards/marcxml/frbr/frbr2html.xsl

./standards/marcxml/validation/schema2validateNoNS.xsl
./standards/marcxml/validation/genvalidate.xsl
./standards/marcxml/validation/marcxmlvalidate.xsl
./standards/marcxml/validation/schema2validate.xsl
./standards/marcxml/validation/validate.xsl
./standards/mets/lc_drafts/stylesheets/profile.xsl
./standards/mets/lc_drafts/stylesheets/xmlverbatim.xsl
./standards/mets/profile_docs/xsd2doc.xsl
./standards/mets/profile_docs/profileXsd2doc.xsl
./standards/mets/profiles/xmlverbatim_mets.xsl
./standards/mets/profiles/echoProfile2html.xsl
./standards/mets/profiles/profile9.xsl
./standards/mets/profiles/LC_profiles/newspaper/ccs2ndnp3.xsl
./standards/mets/profiles/LC_profiles/stylesheets/profile.xsl
./standards/mets/profiles/LC_profiles/stylesheets/xmlverbatim.xsl
./standards/mets/test/stylesheets/profile10trans.xsl
./standards/mets/test/stylesheets/profile10.xsl
./standards/mets/test/stylesheets/profile.xsl
./standards/mets/test/stylesheets/xmlverbatim.xsl
./standards/mets/stylesheets/profile.xsl
./standards/mets/stylesheets/xmlverbatim.xsl
./standards/iso639-5/changes.xsl
./standards/mods/temp/rss.xsl
./standards/mods/rdf/junk/kefo-namespace.xsl
./standards/MODS/temp/rss.xsl
./standards/sru/bibframe/fullDisplay.nate.xsl
./standards/sru/bibframe/fullDisplay.xsl
./standards/sru/bibframe/briefDisplay.xsl
./standards/sru/bibframe/fullDisplay.indexdata.xsl
./standards/test/marcRSS.xsl
./standards/test/date.date-time.xsl
