<?xml version="1.0" encoding="UTF-8"?>
<!-- Update Initial Draft -->
<!-- 3rd November 2004 -->
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" 
xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" 
xmlns:xs="http://www.w3.org/2001/XMLSchema" 
xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" 
xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" 
xmlns:ucp-interfaces="http://www.loc.gov/zing/srw/update/interfaces/" 
xmlns:ucp-xml-binding="http://www.loc.gov/zing/srw/update/xml-binding/"
 xmlns:xcql="http://www.loc.gov/zing/cql/xcql/" 
 xmlns:srw="http://www.loc.gov/zing/srw/" 
 xmlns:diag="http://www.loc.gov/zing/srw/diagnostic/" 
 xmlns:ucp="http://www.loc.gov/zing/srw/update"
  targetNamespace="http://www.loc.gov/zing/srw/update/xml-binding">
<import namespace="http://www.loc.gov/zing/srw/update/interfaces/" location="update-ports.wsdl"/>
<binding name="XML-Binding" type="ucp-interfaces:updateInterface">
<http:binding verb="POST"/>
<operation name="update">
<http:operation location=""/>
<input>
<mime:mimeXml part="body"/>
</input>
<output>
<mime:mimeXml part="body"/>
</output>
</operation>
<operation name="explain">
<http:operation location=""/>
<input>
<mime:mimeXml part="body"/>
</input>
<output>
<mime:mimeXml part="body"/>
</output>
</operation>
</binding>
</definitions>
